# Generated by Django 5.0 on 2024-02-07 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=400)),
                ("name", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("member_id", models.AutoField(primary_key=True, serialize=False)),
                ("member_name", models.CharField(max_length=50)),
                ("show_bought", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Gift",
            fields=[
                ("gift_id", models.AutoField(primary_key=True, serialize=False)),
                ("item_name", models.CharField(max_length=100)),
                ("exact_item", models.BooleanField(default=False)),
                ("multiple", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, max_length=1000)),
                (
                    "date_to_remove",
                    models.DateField(blank=True, default=None, null=True),
                ),
                ("bought", models.BooleanField(default=False)),
                ("links", models.ManyToManyField(blank=True, to="gifts_app.link")),
                (
                    "gift_adder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adding_gift",
                        to="gifts_app.member",
                    ),
                ),
                (
                    "gift_receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiving_gift",
                        to="gifts_app.member",
                    ),
                ),
                (
                    "visible_to",
                    models.ManyToManyField(
                        blank=True, related_name="visible_gifts", to="gifts_app.member"
                    ),
                ),
            ],
        ),
    ]
