# Generated by Django 5.0 on 2024-05-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gifts_app", "0003_remove_gift_bought_remove_gift_visible_to_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gift",
            name="date_to_remove",
        ),
        migrations.AddField(
            model_name="gift",
            name="visible_to",
            field=models.ManyToManyField(
                blank=True, related_name="visible_gifts", to="gifts_app.member"
            ),
        ),
    ]
