# Generated by Django 5.0 on 2024-05-06 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gifts_app", "0004_remove_gift_date_to_remove_gift_visible_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="show_bought",
        ),
    ]
