# Generated by Django 5.0 on 2024-05-09 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gifts_app", "0006_gift_bought_gift_notes_other"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gift",
            old_name="notes_other",
            new_name="other_notes",
        ),
    ]
