# Generated by Django 5.0 on 2024-06-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gifts_app", "0007_rename_notes_other_gift_other_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gift",
            name="bought",
            field=models.CharField(blank="none", max_length=100),
        ),
    ]
